<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DiagnosisTypesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @param $item
     * @return void
     */
    public function run()
    {
        $diagnosisTypes = [
            "46,XX DSD",
            "46,XY DSD",
            "Abscess",
            "Acanthosis nigricans",
            "Accessory breast tissue",
            "Accessory breasts",
            "Achalasia",
            "Achondroplasia",
            "Acne",
            "Acromegaloidism",
            "Acromegaly",
            "Acropachy",
            "Active",
            "Addison disease",
            "Adenoma cystic",
            "Adrenal",
            "Adrenal Crisis",
            "Adrenal cyst",
            "Adrenal endocrine hypertension",
            "Adrenal enlargement",
            "Adrenal fatigue",
            "Adrenal hemorrhage",
            "Adrenal hemorrhage",
            "Adrenal hyperplasia macronodular bilateral",
            "Adrenal hyperplasia micronodular bilateral",
            "Adrenal incidentaloma",
            "Adrenal insufficiency",
            "Adrenal mass",
            "Adrenal myelolipoma",
            "Adrenal thickening",
            "Adrenalectomy",
            "Adrenocortical adenoma",
            "Adrenocortical carcinoma",
            "AF",
            "Aggressive metastatic",
            "Aggressive pituitary tumor",
            "AIDS",
            "AKI",
            "Albinism",
            "Albuminuria",
            "Alcoholic hepatitis",
            "Alcoholic liver disease",
            "Alcoholism",
            "Aldosteronism primary",
            "Allergic rhinitis",
            "Alopecia",
            "Alopecia areata",
            "Alopecia partialis",
            "Alopecia totalis",
            "Amenorrhea primary",
            "Amenorrhea secondary",
            "Amiodarone",
            "Amiodarone-related thyroid dysfunction",
            "Ammar",
            "Amnesia",
            "Amputation",
            "Amyotrophic lateral sclerosis(ALS)",
            "Amyotrophy",
            "Anabolic Steroid and SARMS Abuse",
            "Androgen insensitivity syndrome",
            "Androgen secreting tumor",
            "Androgenic alopecia",
            "Anemia",
            "Aneurysmal bone cyst",
            "Angular stomatitis",
            "Anhidrosis",
            "Ankle",
            "Ankylosing spondylitis",
            "Anorchia",
            "Anosmia",
            "Anovulatory cycle",
            "Anoxic encephalopathy",
            "anti-CCP+VE",
            "anti-CCP+VE",
            "anti-CCP-VE",
            "anti-CCP-VE",
            "anti-GAD+VE",
            "anti-GAD-VE",
            "Antipsychotic drugs hyperglycemia",
            "anti-TG+VE",
            "anti-TG-VE",
            "anti-TPO+VE",
            "anti-TPO-VE",
            "anti-TTG-IgA+VE",
            "anti-TTG-IgA-VE",
            "Aortic aneurysm",
            "Aortic dissection",
            "Aortic regurgitation",
            "Aortic stensois",
            "Aortic valve disease",
            "Aphthous ulcer",
            "Apoplexy",
            "Appendicitis",
            "Arachnoid cyst",
            "Aromatase excess syndrome",
            "ART-artificial insemination (AI)",
            "ART-donor conception",
            "ART-gamete intrafallopian transfer (GIFT)",
            "Artifact",
            "Artificial insemination",
            "ART-intracytoplasmic sperm injection (ICSI)",
            "ART-in-vitro fertilisation (IVF)",
            "ART-ovulation induction (OI)",
            "ART-preimplantation genetic diagnosis (PGD)",
            "ART-surrogacy",
            "ART-unknown",
            "Ascites",
            "Ascites",
            "Asherman syndrome",
            "Aspermia",
            "Asthenospermia",
            "Asthma",
            "Ataxia",
            "Athetosis",
            "Athyrotic",
            "Atrial fibrillation",
            "Attention deficit hyperactivity disorder (ADHD)",
            "Attention-deficit/hyperactivity disorder (ADHD)",
            "Atypical Diabetes mellitus",
            "Atypical femoral fracture",
            "Atypical genitalia",
            "Autistic behaviour",
            "Autoimmune liver disease",
            "Autoimmune polyendocrine syndromes",
            "Autoimmune thyroid disease (AITD)",
            "Autonomic neuropathy",
            "Autosomal dominant",
            "Autosomal dominant polycystic kidney disease(ADPKD)",
            "Autosomal recessive",
            "Autosomal recessive polycystic kidney disease(ARPKD)",
            "Avascular necrosis",
            "Azoospermia",
            "B12 deficiency",
            "Background",
            "Bardet-Biedl syndrome",
            "Bariatric surgery Duodenal switch with biliopancreatic diversion",
            "Bariatric surgery Laparoscopic adjustable gastric banding",
            "Bariatric surgery Mini-gastric bypass",
            "Bariatric surgery Roux-en-Y gastric bypass",
            "Bariatric surgery Sleeve gastrectomy",
            "Bariatric surgery unknown",
            "Basal cell carcinoma",
            "Basal ganglia calcification",
            "Beckwith–Wiedemann syndrome",
            "Behcet disease",
            "Bell's palsy",
            "Bethesda I nondiagnostic or unsatisfactory",
            "Bethesda II benign",
            "Bethesda III atypia of undetermined significance or follicular lesion of undetermined significance (AUS/FLUS)",
            "Bethesda IV follicular neoplasm or suspicious for a follicular neoplasm",
            "Bethesda V suspicious for malignancy",
            "Bethesda VI malignant",
            "Bilateral",
            "Bilateral adrenalectomy",
            "Biliary cirrhosis primary",
            "Biochemical incomplete response",
            "Biochemical persistence",
            "Biological agents",
            "Bioprosthesis valve",
            "Bioprosthetic aortic valve",
            "Bioprosthetic mitral valve",
            "Bitemporal hemianopia",
            "Bleeding per rectum",
            "Blind",
            "Blood transfusion",
            "Boil",
            "Bowel",
            "BPH",
            "BPH",
            "Brachial plexus injury",
            "Brachial plexus neuropathy",
            "Brachydactyly(shortness of the fingers and toes)",
            "Bradycardia",
            "Brain",
            "Brain calcification",
            "Brain stem",
            "Brain tumor",
            "Branchial cleft cyst",
            "Breast",
            "Breast atrophy",
            "Breast implant",
            "Bronchiectasis",
            "Bronchus",
            "Brown Tumour(osteitis fibrosa cystica)",
            "Brucellosis",
            "Bruxism (teeth grinding)",
            "Buccal mucosa",
            "Budd-Chiari syndrome",
            "Buffalo hump",
            "Bullosis Diabeticorum",
            "Cachexia",
            "Café au lait spots",
            "CAH 11-beta-hydroxylase deficiency",
            "CAH 17α-hydroxylase deficiency",
            "CAH 21-hydroxylase deficiency",
            "CAH 3-beta-hydroxysteroid dehydrogenase deficiency",
            "CAH Cholesterol sidechain cleavage enzyme",
            "CAH Congenital adrenal hyperplasia",
            "CAH Congenital adrenal hyperplasia classic",
            "CAH Congenital adrenal hyperplasia nonclassic",
            "CAH Lipoid",
            "CAH P450-oxidoreductase (POR)",
            "Calcium-sensing receptor disroder",
            "Callus",
            "Cancer",
            "Carbuncle",
            "Carcinoid tumor",
            "Card",
            "Cardiac Resynchronization Therapy",
            "Cardiac Resynchronization Therapy (CRT)",
            "Cardiomyopathy",
            "Cardiomyopathy dilated",
            "Cardiomyopathy hypertrophic",
            "Cardiomyopathy restrictive",
            "Carney complex",
            "Carpal",
            "Carpal tunnel syndrome",
            "Case report",
            "Castor oil",
            "Cataract",
            "Cavernous invasion",
            "Celiac disease",
            "Cellulitis",
            "Cerebellar hemangioblastomas",
            "Cerebral palsy(CP)",
            "Cerebral venous sinus thrombosis (CVST)",
            "Cerebral venous thrombosis",
            "Cervical",
            "Cervical myelopathy",
            "CGHD",
            "Charcot neuroarthropathy",
            "Charcot-Marie-Tooth disease",
            "Checkpoint inhibitors diabetes (CPI-DM)",
            "Chediak-Higashi syndrome",
            "Chemotherapeutic effect endocrine organs",
            "Chemotherapy",
            "Chiasmal compression",
            "Chiasmal herniation",
            "Chickenpox",
            "Chloasma",
            "Cholangiocarcinoma",
            "Cholecystectomy",
            "Cholecystitis",
            "Cholestasis",
            "Cholesterol side-chain cleavage enzyme",
            "Chorea",
            "Choreoathetosis",
            "Chorioretinitis",
            "Chronic",
            "Chronic diarrhea",
            "Chronic inflammatory demyelinating polyneuropathy (CIDP)",
            "Chronic kidney disease-mineral and bone disorder (CKD-MBD)",
            "Chronic rejection",
            "Chrousos syndrome",
            "Cirrhosis",
            "CKD",
            "Claustrophobia",
            "Clavicle",
            "Cleft palate",
            "Climacteric symptoms",
            "Clinically non-functioning pituitary adenoma(NFPA)",
            "Cliteromegaly",
            "CLL",
            "Colectomy",
            "Colles' fracture",
            "Collision/Composite Tumors",
            "Colloid cyst of the third ventricle",
            "Colon",
            "Combined mitral valve disease",
            "Confusion in elderly",
            "Congenital",
            "Congenital dyserythropoietic anemias",
            "Congenital hip dislocation",
            "Congenital hyperbilirubinemia",
            "Congenital Hyperinsulinism",
            "Congenital immunodeficiency",
            "Congenital methemoglobinemia",
            "Conns syndrome",
            "Constipation",
            "COPD",
            "Corneal transplant",
            "Cornelia de Lange syndrome",
            "Coronary angiography",
            "Corpus callosum agenesis",
            "Corticotropinoma",
            "Co-secreting adenomas",
            "Cough",
            "COVID-19",
            "CPAP",
            "Cranial",
            "Craniectomy",
            "Craniopharyngioma",
            "Cretinism",
            "Cretinism",
            "Crohn's disease",
            "Cryptorchidism",
            "CSF Diversion",
            "CSF rhinorrhea",
            "Cured",
            "Cushing disease",
            "Cushing disease cyclical",
            "Cushing syndrome",
            "Cushing syndrome ACTH dependent",
            "Cushing syndrome ACTH independent",
            "Cushing syndrome subclinical",
            "CVA",
            "Cyberknife",
            "Cystinosis",
            "Dead in bed syndrome",
            "Deaf-mute",
            "Deafness",
            "Death",
            "Deep voice",
            "Defaulter",
            "Delayed puberty",
            "Delayed thelarche",
            "DELTA",
            "Dementia",
            "Depression",
            "Dermatitis herptifrom",
            "Dermatomyositis",
            "Dermoid cyst",
            "Dermopathy",
            "Desmoplastic small round cell tumor",
            "Developmental delay",
            "Dextrocardia",
            "Diabetes insipidus",
            "Diabetes mellitus in young (youth)",
            "Diabetic foot",
            "Diabetic hand",
            "Diabetic nephropathy",
            "Dicytopenia",
            "Discrepancy",
            "Disorders of sex development (DSD)",
            "Disproportionate",
            "Disproportionate short stature (DSS)",
            "DKA",
            "DM",
            "DM LADA",
            "DM MODY",
            "DM Others",
            "DM pregnancy",
            "DM/Type 1",
            "Domiciliary Oxygen Therapy",
            "Dopamine agonist intolerance",
            "Doping",
            "Double Diabetes mellitus",
            "Double Pituitary Adenoma",
            "Double surgery",
            "Down syndrome",
            "Drug addict",
            "Drug induced hyperprolactinemia",
            "Dual Functioning Pituitary Tumor",
            "Dual-staining pituitary adenomas",
            "Duchenne muscular dystrophy",
            "Dumping syndrome",
            "Duodenal biopsy",
            "Duodenal biopsy",
            "Duodenal diverticulum",
            "Dupuytren contracture",
            "DVT",
            "Dysgeusia",
            "Dysmenorrhea",
            "Dyspareunia",
            "Dyspareunia",
            "Dysphagia",
            "Dysphonia",
            "Dystonia",
            "Early-onset androgenetic alopecia",
            "Ectodermal dysplasias",
            "Ectopic ACTH Syndrome",
            "Ectopic pituitary adenoma",
            "Ectopic thyroid",
            "Eczema",
            "Edema",
            "Ejacualtion delyed",
            "Ejacualtion premature",
            "Ejacualtion retrograde",
            "Ejaculaiton delayed",
            "Ejaculate dry(Dry orgasm)",
            "Empty sella syndrome-primary",
            "Empty sella syndrome-secondary",
            "Encephalitis",
            "Encephalopathy",
            "Endometriosis",
            "Endometriosis",
            "Endometrium",
            "Eosinophilia",
            "Eosinophilic esophagitis",
            "Epidermoid cyst ",
            "Epilepsy",
            "Epistaxis",
            "Erb's palsy",
            "Erectile dysfunction",
            "Eruptive",
            "Erythema annulare",
            "Erythema nodosum",
            "Escalation",
            "Esophageal candidiasis",
            "Esophageal varices",
            "ESRD",
            "Essential thrombocythemia",
            "Euadrenal",
            "Euglycemic ketosis",
            "Eumenorrheic",
            "Eunuchoidism",
            "Euthyroid",
            "Euthyroid hyperthyroxinemia",
            "Euthyroid hypertriiodothyroninemia",
            "Euthyroid hypothyroxinemia",
            "Eventration of diaphragm",
            "Excellent response",
            "Exophthalmos",
            "Exophytic pituitary adenoma",
            "External beam radiotherapy (EBRT)",
            "Facial myokymia",
            "Factitious",
            "Factor VIII inhibitors",
            "Failure to thrive(FTT)",
            "Falling attack",
            "Falling attacks",
            "Familial",
            "Familial chylomicronemia syndrome",
            "Familial Dysalbuminemic Hyperthyroxinemia",
            "Familial hypocalciuria hypercalcemia(FHH)",
            "Fanconi anemia",
            "Fanconi syndrome",
            "Fasting",
            "Fat redistribution",
            "Favism",
            "Female pattern hair loss (FPHL)",
            "Feminizing ovarian tumors",
            "Femoral head",
            "Femoral neck",
            "Femoral shaft",
            "Fibroid",
            "Fibromyalgia",
            "Fibrosing alveolitis",
            "Fibula",
            "Fistula in ano",
            "Floppy baby(hypotonia)",
            "Flushing",
            "Folliculitis",
            "Food allergy",
            "Food poisoning",
            "Foot Corn",
            "Foot drop",
            "Fracture",
            "Fracture fragility",
            "Freestyle libre",
            "Frontal meningioma",
            "Frozen shoulder",
            "Fulminant type 1 Diabetes mellitus",
            "Functional hypogonadism(Non-gonadal illness syndrome)",
            "Galactorrhea",
            "Galactosemia",
            "Gall stone",
            "Gallbladder",
            "Gamma knife",
            "Gangrene",
            "Gastric bypass surgery",
            "Gastroparesis",
            "Gastrostomy",
            "Gaucher disease",
            "Generalized Glucocorticoid Resistan",
            "Genitoplasty",
            "Genu valgum",
            "Genu Varum",
            "Germ cell tumor",
            "Germinoma",
            "Gestational diabetes mellitus",
            "Gestational transient thyrotoxicosis",
            "Gestational trophoblastic disease",
            "Giant",
            "Giant cell granuloma",
            "Gigantism",
            "Gigantomastia",
            "Gilbert syndrome",
            "GIT bleeding",
            "Gitelman syndrome",
            "Glaucoma",
            "Glaucoma",
            "Glaucoma",
            "Glioma",
            "Globus sensation",
            "Glomerulonephritis",
            "Glucocorticoid induced osteoporosis",
            "Glucocorticoids misuse",
            "Glycogen storage disease",
            "Glycosuria",
            "Gonadal dysgenesis",
            "Gonadal dysgenesis (Swyer syndrome)(46XY gonadal dysgenesis)",
            "Gonadal dysgenesis (Turner syndrome)",
            "Gonadal dysgenesis(46XX gonadal dysgenesis)",
            "Gonadal dysgenesis(Mixed)",
            "Gonadectomy",
            "Gonadoplasty",
            "Gout",
            "Granuloma annulare",
            "Graves disease",
            "Gravitational edema",
            "Growth hormone deficiency(GHD)",
            "Growth hormone insensitivity(Laron syndrome)",
            "Guillain Barre syndrome",
            "Gynecomastia",
            "Hair loss(defluvium)",
            "HAIR-AN syndrome",
            "Halitosis",
            "Hamartoma",
            "Hammer toe",
            "Hashimoto thyroiditis",
            "HB C disease(Hb CC)",
            "HB C trait",
            "HbA1c Discrepancy",
            "Head injury",
            "Headache",
            "Heart block",
            "Heart failure",
            "hemangioma",
            "Hematemesis",
            "Hematospermia",
            "Hematuria",
            "Hemiatrophy",
            "Hemihypertrophy",
            "Hemiplegia",
            "Hemochromatosis",
            "Hemodialysis",
            "Hemoglobin D disease(HbD)",
            "Hemoglobin H disease",
            "Hemolytic anemia",
            "Hemophilia A",
            "Hemoptysis",
            "Hemoptysis",
            "Henoch-Schönlein purpura",
            "Hepatitis",
            "Hepatitis B +ve",
            "Hepatitis C +ve",
            "Hepatomegaly",
            "Herbal Medicine",
            "Hermaphroditism",
            "Herpes Zoster",
            "Herpetic gingivostomatitis",
            "Hiccough",
            "Hidradenitis suppurativa",
            "High ACTH",
            "High alkaline phospahatse",
            "High CPK",
            "High DHEA-S",
            "High ESR",
            "High FT4",
            "High HbF",
            "High SHBG",
            "High TT3",
            "Hip",
            "Hirsutism",
            "Hoarseness",
            "Hoarseness of voice",
            "Hodgkin lymphoma",
            "Humerus",
            "Hungry bone syndrome",
            "Hurthle cell adenoma",
            "Hurthle Cell Carcinoma",
            "Hurthle cell tumor",
            "Hydatid cyst",
            "Hydatidiform mole",
            "Hydrocele",
            "Hydrocephalus",
            "Hydronephrosis",
            "Hyperandrogenism",
            "Hypercalcemia",
            "Hypercalciuria",
            "Hyperemesis gravidarum",
            "Hyperglycemia",
            "Hyperhidrosis",
            "Hyperintense T2 weighted image",
            "Hyperkalemia",
            "Hyperlipidemia",
            "Hyperlipidemia familial hypercholesterolemia",
            "Hyperlipidemia hypercholesterolemia",
            "Hyperlipidemia hypertriglyceridemia",
            "Hyperlipidemia mixed",
            "Hypermagnesemia",
            "Hypermobility",
            "Hyperosmolar hyperglycemic state (HHS)",
            "Hyperphagia",
            "Hyperphosphatemia",
            "Hyperpigmentation",
            "Hyperprolactinemia",
            "HyperPTH primary",
            "HyperPTH secondary",
            "HyperPTH tertiary",
            "HyperPTH unknown",
            "Hyperreninemia",
            "Hypersexuality",
            "Hypersplenism",
            "Hypertension",
            "Hyperthyroidism",
            "Hyperthyroidism subclinical",
            "Hyperthyroidism trophoblastic",
            "Hypertrophic scar",
            "Hypoactive sexual desire disorder (HSDD)",
            "Hypoaldosteronism",
            "Hypoaldosteronism hyporeninemic",
            "Hypocalcemia",
            "Hypochondriasis",
            "Hypoglycemia",
            "Hypoglycemia fasting",
            "Hypoglycemia hyperinsulinemic",
            "Hypoglycemia postprandial",
            "Hypogonadism",
            "Hypogonadism hypergonadotropic",
            "Hypogonadism hypogonadotropic",
            "Hypointense T2 weighted image",
            "Hypokalemia",
            "Hypomagnesemia",
            "Hyponatremia",
            "Hypophosphatasia",
            "hypophosphatemia",
            "Hypophysectomy transcranial",
            "Hypophysectomy transsphenoidal",
            "Hypophysitis",
            "Hypopituitarism",
            "HypoPTH",
            "HypoPTH postthyroidectomy",
            "Hypospadias",
            "Hypotension",
            "Hypothalamic disorder",
            "Hypothalamic hamartoma",
            "Hypothalamic obesity",
            "Hypothalamus",
            "Hypothyroidism",
            "Hypothyroidism central",
            "Hypothyroidism congenital",
            "Hypothyroidism subclinical",
            "Hysterectomy",
            "Hysterectomy with bilateral salpingectomy",
            "Hysterectomy with Bilateral Salpingo-Oophorectomy",
            "IBD",
            "IbrahimA",
            "IBS",
            "Ichthyosis",
            "Icthyosis",
            "IDA",
            "Idiopathic",
            "Idiopathic intracranial hypertension (IIH)",
            "IFG",
            "IgA nephropathy",
            "IgG4-related orbitopathy",
            "IGT",
            "IHD",
            "IHD CABG",
            "IHD PCI",
            "IHD STEMI",
            "IHD three-vessels disease",
            "IHD two-vessels disease",
            "ILD",
            "Immunosuppression",
            "Immunotherapy",
            "Impulse control disorder",
            "inactivating PTH/PTHrP signalling disorder (iPPSD)",
            "Inborn errors of metabolism(IEM)",
            "Indeterminate response",
            "Infant of diabetic mother",
            "Infertility primary",
            "Infertility secondary",
            "Ingrowing toenail",
            "Insomnia",
            "Insulin allergy",
            "Insulin edema",
            "Insulin injection site adverse effect",
            "Insulin lipoatrophy",
            "Insulin lipohypertrophy",
            "Insulin neuritis",
            "Insulin Pump",
            "Insulin resistance (IR)",
            "Insulin sequestration",
            "Interferon related thyroid disease",
            "Intertrigo",
            "Intestinal obstruction",
            "Intestinal obstruction",
            "Intestinal pseudo-obstruction",
            "Intra articular steroid injection",
            "Intracerebral hemorrhage",
            "Intracranial calcification",
            "Intracranial germ cell tumour",
            "Intracytoplasmic sperm injection (ICSI)",
            "Intraoperative PTH estimation",
            "Intravitreal injection",
            "Intrinsic minus foot",
            "I-Port",
            "Iron overload disorder",
            "Irregular menstruation",
            "Irritable bladder",
            "Isointense T2 weighted image",
            "Isolated hyperthyroxinemia",
            "Isolated hypothyroxinemia",
            "Isolated maternal hypothyroxinemia",
            "Isthmus nodule",
            "Itching",
            "ITP",
            "Jaundice",
            "Juvenile",
            "Juvenile chronic arthritis",
            "Juvenile myxedema",
            "Kallmann syndrome",
            "Keloid",
            "ketosis",
            "Ketosis-prone Diabetes mellitus (KPD)",
            "kidney stone",
            "kidney transplantation",
            "Klinefelter’s syndrome",
            "Knock knee",
            "Kyphoscoliosis",
            "Kyphosis",
            "Lack of family support",
            "Lactotroph hyperplasia",
            "Laryngeal",
            "Laryngectomy",
            "Laser",
            "Late onset hypogonadism(LOH)",
            "Late-onset hypogonadism",
            "Lateral malleolus",
            "Laurence Moon Biedl syndrome",
            "LBBB",
            "Learning disability",
            "Leishmaniasis",
            "Leptin deficiency",
            "Leukemia",
            "Leukoerythroblastic blood picture",
            "Leukopenia",
            "Lichen planus",
            "Liddle syndrome",
            "Lingual thyroid",
            "Lipedema",
            "Lipodystrophy",
            "Lipoid pneumonia",
            "Lipoma",
            "Liraglutide (Saxenda)",
            "Livedo reticularis",
            "Liver",
            "Liver transplantation",
            "Loss of awareness",
            "Loss of libido",
            "Low bone mineral density",
            "Low FT4",
            "Low HDL",
            "Low SHBG",
            "Low T3",
            "Lowe syndrome(Oculocerebrorenal syndrome)",
            "LP",
            "lung tumor",
            "LUTS",
            "LVH",
            "Lymph node",
            "Lymph node metastasis",
            "Lymphadenopathy",
            "Lymphedema",
            "Macroadenoma",
            "Macrocytic anemia",
            "Macroglossia",
            "Macroorchidism",
            "Macroprolactinemia",
            "Maculopathy",
            "Mahmood",
            "Malabsorption",
            "Malignant",
            "Mallory weiss syndrome",
            "Marfan syndrome",
            "Marfanoid habitus",
            "Mastalgia",
            "Mastectomy",
            "Mauriac syndrome",
            "Mayer-Rokitansky-Küster-Hauser syndrome",
            "McCune–Albright syndrome",
            "MDS",
            "Measles",
            "Mechanical prosthesis",
            "Mediastinal mass",
            "Megaloblastic anemia",
            "Melanoma",
            "Melena",
            "Meningioma",
            "Meningioma Cerebellopontine angle",
            "Meningioma choroid plexus",
            "Meningioma convexity",
            "Meningioma falx cerebri",
            "Meningioma optic nerve",
            "Meningioma Parasagittal",
            "Meningioma Parasellar",
            "Meningioma Petroclival",
            "Meningioma Sphenoid wing",
            "Meningioma suprasellar",
            "Meningioma Suprasellar",
            "Meningioma tentorium cerebelli",
            "Meningioma third ventricle",
            "Meningioma tuberculum Sellae",
            "Meningitis",
            "Menopause",
            "Menopause premature",
            "Menorrhagia",
            "Mental retardation",
            "Mental subnormality",
            "Mesenteric ischemia",
            "Mesenteric venous thrombosis",
            "Metabolic syndrome",
            "Metabolic syndrome",
            "Metacarpal",
            "Metallic aortic valve",
            "Metallic mitral valve",
            "Metallic prosthesis",
            "Metallic tricuspid valve",
            "Metastasis",
            "Metastatic",
            "Metastatic pheochromocytoma",
            "Metastatic thyroid cancer without identifiable primary tumor",
            "Metatarsal",
            "Metformin intolerance",
            "Methemoglobinemia",
            "Microadenoma",
            "Microalbuminuria",
            "Microcephaly",
            "Micropenis",
            "Migraine",
            "Mild autonomous cortisol excess (MACE)",
            "Mitral regurgitation",
            "Mitral stenosis",
            "Mitral valve disease",
            "Mixed connective tissue disease",
            "Morning sickness",
            "Motion sickness",
            "Motor neuron disease(MND)",
            "Mouth ulcer",
            "Mucocutaneous Candidiasis",
            "Mucopolysaccharidosis",
            "Mucormycosis",
            "Mucosal neuromas",
            "Mullerian agenesis",
            "Multiple endocrine neoplasia",
            "Multiple endocrine neoplasia type 1",
            "Multiple endocrine neoplasia type 2",
            "Multiple endocrine neoplasia type 2A",
            "Multiple endocrine neoplasia type2B",
            "Multiple lipomatosis",
            "Multiple myeloma",
            "Multiple sclerosis",
            "Mumps",
            "Muscle wasting",
            "Muscular dystrophy",
            "Mute",
            "Myasthenia gravis",
            "Mycostatin dro1",
            "Myelocele",
            "Myeloproliferative disorder",
            "Myotonia",
            "Myotonia congenita",
            "Myotonic dystrophy",
            "Myotonic dystrophy",
            "Myxodema Coma",
            "NAFLD",
            "Nail dystrophy",
            "Narcotic addict",
            "NASH",
            "Nasopharyngeal",
            "Natural killer cell deficiency",
            "Neck dissection",
            "Neck webbing",
            "Necrobiosis lipoidica diabeticorum",
            "Necrotizing  fasciitis",
            "Neglected",
            "Nelson’s syndrome",
            "Neonatal Diabetes mellitus",
            "Neonatal hypoglycemia",
            "Nephrectomy",
            "Nephrogenic",
            "Nephrotic syndrome",
            "Nesidioblastosis",
            "Neuroendocrine tumors (NETs)",
            "Neurofibroma",
            "Neurofibromatosis",
            "Neurogenic bladder",
            "Neurosis",
            "Neutropenia",
            "New",
            "NIFTP",
            "No adenoma",
            "No HbA1c peak (YY)",
            "Nocturia",
            "Nocturnal",
            "Nocturnal enuresis",
            "Nocturnal leg cramps",
            "Nodular thyroid disease",
            "Non-Hodgkin lymphoma (NHL)",
            "Non-thyroidal illness syndrome",
            "Nontumoral hyperprolactinemia",
            "Noonan syndrome",
            "Normocalcemic",
            "Normocalcemic hyperPTH",
            "Novopen",
            "NSAIDS",
            "Nystagmus",
            "Nystagmus",
            "Obesity Class 1",
            "Obesity Class 2",
            "Obesity Class 3",
            "Obesity hypoventilation syndrome",
            "Obesity stage 1",
            "Obesity stage 2",
            "Obesity stage 3",
            "Obesity stage 4",
            "Obsessive compulsive neurosis",
            "Obsessive compulsive neurosis",
            "Obstructive jaundice",
            "OCPs",
            "Odontogenesis imperfecta",
            "Oligomenorrhea",
            "Oligospermia",
            "Oncocytoma",
            "Onycholysis",
            "Oophorectomy",
            "Open mitral valvotomy",
            "Ophthalmoplegia",
            "Optic atrophy",
            "Optic neuritis",
            "Orbital pseudotumor",
            "Orchidopexy",
            "Orchidopexy",
            "Orchiectomy",
            "Orchitis",
            "Oropharyngeal",
            "Oropharyngeal tumor",
            "Osteitis fibrosa cystica",
            "Osteogenesis imperfecta",
            "Osteogenic sarcoma",
            "Osteomalacia",
            "Osteomyelitis",
            "Osteonecrosis of the Jaw",
            "Osteopenia",
            "Osteoporosis",
            "Others",
            "Otitis media",
            "Ovarian cyst",
            "Ovarian hyperthecosis",
            "Ovarian tumor",
            "Ovary",
            "Overweight",
            "Ovotesticular DSD",
            "P450-oxidoreductase (POR) deficiency",
            "Pacemaker",
            "Paget schroetter syndrome",
            "Pancrease",
            "Pancrease fatty",
            "Pancreatectomy",
            "Pancreatic mass",
            "Pancreatic pseudocyst",
            "Pancreatitis",
            "Pancytopenia",
            "Papilledema",
            "Papilloedema",
            "Paraganglioma",
            "Paraplegia",
            "Paraplegia flaccid",
            "Paraplegia spastic",
            "Parkinsonism",
            "Paronychia",
            "Parotid",
            "Parotid swelling",
            "Partial",
            "Partial",
            "Partial remission phase of Diabetes mellitus (honeymoon period)",
            "PCOS",
            "Pemphigoid",
            "Pemphigus vulgaris",
            "Pendred syndrome",
            "Penile Curvature (Peyronie's Disease)",
            "Penile implant",
            "Penile prosthesis",
            "Percutaneous ethanol injection (PEI)",
            "Periampullary",
            "Perianal",
            "Perianal abscess",
            "Perianal fistula",
            "Pericardial effusion",
            "Periodic paralysis",
            "Peripartum",
            "Peripheral neuropathy",
            "Peripheral vascular disease",
            "Peritonitis",
            "Persistence",
            "Persistent",
            "Persistent hyperinsulinemic hypoglycemia of infancy (PHHI)",
            "Pes cavus",
            "Peutz-Jeghers syndrome",
            "Pharyngeal pouch",
            "Pheochromocytoma",
            "Phocomelia",
            "Physiologic hypercortisolism (pseudCushing syndrome)",
            "Pica",
            "Pigmentation",
            "Pigmentation",
            "Pigmentation freckling",
            "Pioglitazone(Actos)",
            "Pituitary",
            "Pituitary adenoma",
            "Pituitary artifact",
            "Pituitary asymmetry",
            "Pituitary cyst",
            "Pituitary enlargement",
            "Pituitary gigantism",
            "Pituitary incidentaloma",
            "Pituitary neuroendocrine tumor (PitNET)",
            "Pituitary stalk interruption syndrome",
            "Pituitary tumor",
            "Pityriasis versicolor",
            "Plasmapheresis",
            "Pleomorphic adenoma",
            "Pleomorphic adenoma",
            "Pleural effusion",
            "Pleural effusion",
            "Pneumonia",
            "Pneumonia",
            "Pneumonia",
            "Pneumothorax",
            "Poliomyelitis",
            "Polycythemia",
            "Polycythemia rubra vera",
            "Polydactyly",
            "Polyhydramnios",
            "Polymenorrhea",
            "Polymyalgia rheumatica",
            "Polymyositis",
            "Polyostotic fibrous dysplasia",
            "Polyuria",
            "Polyuria-Polydipsia Syndrome",
            "Pompe disease",
            "Portal hypertension",
            "Portal vein thrombosis",
            "Portal vein thrombosis",
            "Post-coital Headache",
            "Post-covid syndrome",
            "Postherpetic neuralgia",
            "Post-inflammatory hyperpigmentation",
            "Postmenopausal",
            "Postmenopausal bleeding",
            "Postmenopausal hirsutism",
            "Postpartum Depression",
            "Postpartum Thyroiditis",
            "Post-pill amenorrhea",
            "Posttransplantation Diabetes Mellitus (PTDM)",
            "Post-traumatic hypopituitarism",
            "Postural hypotension",
            "Prader Willi syndrome",
            "Precocious Pseudopuberty",
            "Precocious pubarche",
            "Precocious puberty",
            "Precocious puberty central",
            "Precocious puberty peripheral",
            "Prediabetes",
            "Preeclampsia",
            "Pregestational DM",
            "Pregnancy",
            "Premature Adrenarche",
            "Premature menarche",
            "Premature Menopause",
            "Premature ovarian insufficiency",
            "Premature thelarche",
            "Premenstrual syndrome",
            "Premenstrual tension",
            "Pretibial myxedema",
            "Priapism",
            "Primary",
            "Primary pigmented nodular adrenocortical disease (PPNAD)",
            "Prolactinoma",
            "Proptosis",
            "Prostate",
            "Prostatectomy",
            "Prostatism",
            "Proximal myopathy",
            "Pruritus vulvae",
            "Pseudoacromegaly",
            "Pseudohyponatremia",
            "PseudohypoPTH",
            "PseudopseudohypoPTH",
            "Psoriasis",
            "Psoriatic arthritis",
            "Psychosis",
            "Psychosocial short stature",
            "PTH",
            "PTH adenoma",
            "PTH carcinoma",
            "PTH hyperplasia",
            "PTHectomy",
            "Puberty disorders",
            "Pulmonary",
            "Pulmonary embolism",
            "Pulmonary fibrosis",
            "Pulmonary hypertension",
            "Pulmonary valve stenosis",
            "PUO",
            "PVD",
            "Pyelonephritis",
            "Quadriplegia",
            "Quervain thyroiditis",
            "Radioactive Iodine",
            "Radiofrequency ablation",
            "Radius",
            "RAF",
            "Ramadan",
            "Rathke's cleft cyst",
            "Raynaud's phenomenon",
            "Reactive arthritis",
            "Rectum",
            "Recurrence",
            "Recurrent",
            "Recurrent kidney stone former",
            "Recurrent laryngeal nerve injury",
            "Refactory cytopenia with multilineage dysplasia(RCMD)",
            "Refectory",
            "Refeeding syndrome",
            "RefractoryTSH",
            "Rejection",
            "Relapse",
            "Remission",
            "Remission of Diabetes mellitus",
            "Renal angiomyolipomas",
            "Renal artery stenosis",
            "Renal cell carcinoma",
            "Renal cyst",
            "Renal tubular acidosis",
            "Resistant",
            "Resistant hypertension",
            "Respiratory failure",
            "Restless leg syndrome",
            "Restless legs syndrome",
            "Restrictive",
            "Restrictive thyroid ophthalmopathy",
            "Retinal artery occlusion",
            "Retinal detachment",
            "Retinal hemorrhage",
            "Retinal vein occlusion",
            "Retinitis pigmentosa",
            "Retinopathy nonproliferative",
            "Retinopathy proliferative",
            "Retractile testicle",
            "Retractile testis",
            "Retrosternal",
            "Rhabdomyolysis",
            "Rheumatic heart disease",
            "Rheumatoid arthritis",
            "Rheumatoid factor +ve",
            "Rheumatoid factor-ve",
            "Rickets",
            "Rickets hypophosphatemic",
            "Rickets vitamin D dependent",
            "Rickets vitamin D resistant",
            "Riedel thyroiditis",
            "Russell-Silver syndrome",
            "Sacral",
            "Saddle nose",
            "Salivary gland",
            "Salivary gland tumor",
            "Sarcoma",
            "Saxenda",
            "Schmidt syndrome",
            "Schwannoma",
            "Sciatica",
            "Sclerodactyly",
            "Sclerosing cholangitis primary",
            "Scorpion bite",
            "Screening",
            "Seckel syndrome",
            "Secondaries",
            "Secretory",
            "Seizure",
            "Sellar Mass",
            "Semaglutide (Ozympic)",
            "Sertoli cell-only syndrome",
            "Severe hypertriglyceridemia",
            "SGLT2",
            "Sheehan syndrome",
            "Short stature",
            "Short stature Idiopathic (ISS)",
            "SIADH",
            "Sicca syndrome",
            "Sick sinus syndrome",
            "Sickle cell anemia",
            "Sickle cell disease",
            "Sickle thalassemia",
            "Sickler (trait)",
            "Simple virilizing CAH",
            "Sinusitis",
            "Situs inversus",
            "Sjogren's syndrome",
            "Skeletal dysmorphia",
            "Skeletal dysplasia",
            "SLE",
            "Sleep apnea syndrome",
            "Sleeve gastrectomy",
            "Slipped femoral epiphysis",
            "Slipping slipper sign",
            "Small for gestational age(SGA)",
            "Snake bite",
            "Somatization",
            "Sphenoid invasion",
            "Spider bite",
            "Spinal canal stenosis",
            "Spinocerebellar ataxia",
            "Splenectomy",
            "Splenomegaly",
            "Spondyloarthropathy",
            "Stage I",
            "Stage II",
            "Stage III",
            "Stage IVA",
            "Stage IVB",
            "Stalk lesions",
            "Stalk thickening",
            "Stammering",
            "Statin induced muscle injury",
            "Statin-Associated Muscle Symptoms",
            "Stereotactic radiosurgery",
            "Steroid 5-alpha-reductase 2 deficiency",
            "Still disease",
            "Stomach",
            "Striae",
            "Stridor",
            "Structural incomplete response",
            "Structural persistence",
            "Sturge-Weber syndrome",
            "Subarachnoid hemorrhage",
            "Subconjunctival hemorrhage",
            "Submandibular gland swelling",
            "Sudeck's osteodystrophy",
            "Supplement Abuse",
            "Supraclavicular fat pads",
            "Suprasellar",
            "Sura",
            "Surgical failure",
            "SVC Syndrome",
            "Sweating",
            "Syme Amputation",
            "Symptomatic",
            "Syncope",
            "Syndactyly",
            "Systemic sclerosis (scleroderma)",
            "T3 thyrotoxicosis",
            "Talipes equinovarus",
            "Tall stature",
            "Tarsal",
            "Tendinous",
            "Teratoma",
            "Testicle",
            "Testicular regression syndrome(Vanishing Testes)",
            "Testicular seminoma",
            "Testicular teratoma",
            "Thalassemia",
            "Thalassemia alpha",
            "Thalassemia major",
            "Thalassemia minor beta",
            "Thioamides",
            "Thioamides side effect",
            "Three vessels disease",
            "Thrice",
            "Thrice",
            "Thromboangiitis obliterans (Buerger's disease)",
            "Thrombocytopenia",
            "Thymoma",
            "Thyroglossal duct cysts",
            "Thyroid",
            "Thyroid abscess",
            "Thyroid cancer",
            "Thyroid cancer anaplastic",
            "Thyroid cancer follicular",
            "Thyroid cancer lymphoma",
            "Thyroid cancer medullary (MTC)",
            "Thyroid cancer papillary",
            "Thyroid cancer papillary  columar cell",
            "Thyroid cancer papillary  conventional",
            "Thyroid cancer papillary  with dedifferenatiation to anaplastic carcinoma",
            "Thyroid cancer papillary classic",
            "Thyroid cancer papillary clear cell,
        Thyroid cancer papillary cribriform morular",
            "Thyroid cancer papillary combined papillary and medullary carcinoma",
            "Thyroid cancer papillary diffuse sclerosing",
            "Thyroid cancer papillary fasciitis-like stroma",
            "Thyroid cancer papillary follicular variant",
            "Thyroid cancer papillary Macrofollicular",
            "Thyroid cancer papillary microcarcinomas",
            "Thyroid cancer papillary oncocytic",
            "Thyroid cancer papillary prominent hobnail features",
            "Thyroid cancer papillary solid",
            "Thyroid cancer papillary tall cell",
            "Thyroid eye disease (TED)",
            "Thyroid follicular adenoma",
            "Thyroid goiter",
            "Thyroid hormone malabsorption",
            "Thyroid hormone resistance (THR)",
            "Thyroid nodule",
            "Thyroid pregnancy",
            "Thyroid storm",
            "Thyroidectomy completion",
            "Thyroidectomy lobectomy",
            "Thyroidectomy lobo-isthmectomy",
            "Thyroidectomy subtotal",
            "Thyroidectomy total",
            "Thyroidectomy unknown",
            "Thyroiditis",
            "Thyrotoxicosis",
            "Thyrotroph hyperplasia",
            "Thyroxine malabsorption",
            "TIA",
            "Tibia",
            "Tics",
            "Tinea pedis",
            "Tinnitus",
            "Tongue",
            "Torticollis spasmodic",
            "Total",
            "Total hip replacement",
            "Total knee replacement",
            "Toxic adenoma",
            "Toxic epidermolysis",
            "TRAb+VE",
            "TRAb-VE",
            "Transaminitis",
            "Transgender female-to-male(Transman)",
            "Transgender male-to-female(Transwoman)",
            "Transient",
            "Transitional cell carcinoma",
            "Treacher Collins syndrome",
            "Treatment-Induced Neuropathy of Diabetes mellitus",
            "Tremor",
            "Triple surgery",
            "Trulicity",
            "TSH-secreting pituitary adenoma",
            "Tuberculosis",
            "Tuberculum sellae",
            "Tuberous sclerosis",
            "Turner syndrome",
            "Twice",
            "Type 3c (pancreatogenic) Diabetes mellitus",
            "Tyrosine kinase inhibitors",
            "Ulcerative colitis",
            "Ulna",
            "Underweight",
            "Undescended testis",
            "Undetermined origin",
            "Unilateral",
            "Urinary bladder",
            "Urine incontinence",
            "Urticaria",
            "Uterine atresia",
            "UTI",
            "Uveitis",
            "Vaccinated",
            "Vaginal bleeding",
            "Valve replacement",
            "Variant window",
            "Varicocele",
            "Vasculitis",
            "Vasculitis",
            "Vasovagal syncope",
            "Vegetarian",
            "Ventriculoperitoneal shunt",
            "Vertebra",
            "Vertigo",
            "Very severe hypertriglyceridemia",
            "Vestibular",
            "Victoza",
            "Virilization",
            "Virilizing adrenal tumor",
            "Visual field defect",
            "Vitamin D deficiency",
            "Vitamin D insufficiency",
            "Vitamin D intoxication",
            "Vitamin D sufficiency",
            "Vitiligo",
            "Vitrectomy",
            "Volvulus",
            "Von Hippel Lindau Disease",
            "Warfarin",
            "Warts",
            "Weight loss",
            "Weightlifting",
            "Weird thyroid function",
            "Wernicke encephalopathy",
            "Wheelchair bound",
            "Williams syndrome",
            "Wilms tumor",
            "Wilson disease",
            "Wolff-Parkinson-White syndrome",
            "Writer cramp",
            "Xanthelasma",
            "Xanthoma",
            "Xeroderma pigmentosum",
            "Xerosis",
            "Xerostomia",
            "X-linked",
            "Y chromosome microdeletion",
            "Zoledronic acid",
        ];

        foreach ($diagnosisTypes as $type) {
            DB::table('esite_diagnosis_types')->insert([
                'title'       => $type,
                'created_by'  => 1,
                'created_at'  => Carbon::now()
            ]);
        }
    }
}
